In [1]:
#import necessary libraries

In [2]:
import pandas as pd

In [3]:
#declare the variable name and store the csv and open it

In [4]:
df = pd.read_csv("E:\\data cleaning.csv")
df

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
0,4d3db980-46cd-4158-a812-dcb77055d0d2,22-06-2024 04:06,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,FAILED
1,099ee548-2fc1-4811-bf92-559c467ca792,19-06-2024 06:04,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,SUCCESS
2,d4c05732-6b1b-4bab-90b9-efe09d252b99,04-06-2024 04:56,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,SUCCESS
3,e8df92ee-8b04-4133-af5a-5f412180c8ab,09-06-2024 09:56,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,SUCCESS
4,e7d675d3-04f1-419c-a841-7a04662560b7,25-06-2024 08:38,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,SUCCESS
...,...,...,...,...,...,...,...,...
995,843d87b5-902e-4336-9438-aa76d74e13e4,03-07-2024 23:15,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,SUCCESS
996,2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,15-06-2024 15:42,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,FAILED
997,7c38e684-5968-432e-8acb-5bbe0f718fad,18-06-2024 17:27,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,FAILED
998,27624b55-fd6d-45ce-bbc5-0c2958d48865,05-06-2024 21:57,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,FAILED
999,b792bf64-2047-4435-aac1-27ee95b134d6,21-06-2024 15:52,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,SUCCESS

In [5]:
#showing of first 5 datasets

In [6]:
df.head(5)

,Transaction ID,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
0,4d3db980-46cd-4158-a812-dcb77055d0d2,22-06-2024 04:06,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,FAILED
1,099ee548-2fc1-4811-bf92-559c467ca792,19-06-2024 06:04,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,SUCCESS
2,d4c05732-6b1b-4bab-90b9-efe09d252b99,04-06-2024 04:56,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,SUCCESS
3,e8df92ee-8b04-4133-af5a-5f412180c8ab,09-06-2024 09:56,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,SUCCESS
4,e7d675d3-04f1-419c-a841-7a04662560b7,25-06-2024 08:38,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,SUCCESS

In [7]:
#checking of duplicate values

In [8]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [9]:
#counting of duplicate values

In [10]:
df.duplicated().sum()

0

In [11]:
#counting the total null values

In [12]:
df.isnull().sum()

Transaction ID     0
Timestamp          0
Sender Name        0
Sender UPI ID      0
Receiver Name      0
Receiver UPI ID    0
Amount (INR)       0
Status             0
dtype: int64

In [13]:
#changing the index as transaction id

In [14]:
 df1 = df.set_index("Transaction ID")

In [15]:
#checking datatypes

In [16]:
df1.dtypes

Timestamp           object
Sender Name         object
Sender UPI ID       object
Receiver Name       object
Receiver UPI ID     object
Amount (INR)       float64
Status              object
dtype: object

In [17]:
#changing the status interms of 0 and 1 where for success 1 is used and for failure 0 is used

In [18]:
# import skicitlearn

In [19]:
import sklearn

In [20]:
from sklearn.preprocessing  import LabelEncoder
encoder = LabelEncoder()
df1['Status']= encoder.fit_transform(df1['Status'])
print(df1)

                                             Timestamp         Sender Name  \
Transaction ID
4d3db980-46cd-4158-a812-dcb77055d0d2  22-06-2024 04:06           Tiya Mall
099ee548-2fc1-4811-bf92-559c467ca792  19-06-2024 06:04     Mohanlal Bakshi
d4c05732-6b1b-4bab-90b9-efe09d252b99  04-06-2024 04:56         Kismat Bora
e8df92ee-8b04-4133-af5a-5f412180c8ab  09-06-2024 09:56       Ayesha Korpal
e7d675d3-04f1-419c-a841-7a04662560b7  25-06-2024 08:38         Jivin Batta
...                                                ...                 ...
843d87b5-902e-4336-9438-aa76d74e13e4  03-07-2024 23:15          Anay Karan
2dbbb577-4617-44b1-9a51-5fdf18ebb2ab  15-06-2024 15:42      Nirvaan Aurora
7c38e684-5968-432e-8acb-5bbe0f718fad  18-06-2024 17:27  Bhamini Srinivasan
27624b55-fd6d-45ce-bbc5-0c2958d48865  05-06-2024 21:57         Krish Kohli
b792bf64-2047-4435-aac1-27ee95b134d6  21-06-2024 15:52        Diya Trivedi

                                              Sender UPI ID   Receiver Name  \
Transaction ID
4d3db980-46cd-4158-a812-dcb77055d0d2      4161803452@okaxis  Mohanlal Golla
099ee548-2fc1-4811-bf92-559c467ca792      8908837379@okaxis  Mehul Sankaran
d4c05732-6b1b-4bab-90b9-efe09d252b99       4633654150@okybl       Diya Goel
e8df92ee-8b04-4133-af5a-5f412180c8ab  7018842771@okhdfcbank    Rhea Kothari
e7d675d3-04f1-419c-a841-7a04662560b7       1977143985@okybl     Baiju Issac
...                                                     ...             ...
843d87b5-902e-4336-9438-aa76d74e13e4  7041132054@okhdfcbank   Dhanush Salvi
2dbbb577-4617-44b1-9a51-5fdf18ebb2ab       1200592114@okybl     Faiyaz Kara
7c38e684-5968-432e-8acb-5bbe0f718fad     6922445535@okicici     Mishti Kala
27624b55-fd6d-45ce-bbc5-0c2958d48865  4638471232@okhdfcbank      Sahil Bail
b792bf64-2047-4435-aac1-27ee95b134d6       0385561234@oksbi     Dhanuk Mane

                                            Receiver UPI ID  Amount (INR)  \
Transaction ID
4d3db980-46cd-4158-a812-dcb77055d0d2       7776849307@okybl       3907.34
099ee548-2fc1-4811-bf92-559c467ca792      7683454560@okaxis       8404.55
d4c05732-6b1b-4bab-90b9-efe09d252b99     2598130823@okicici        941.88
e8df92ee-8b04-4133-af5a-5f412180c8ab      2246623650@okaxis       8926.00
e7d675d3-04f1-419c-a841-7a04662560b7       5245672729@okybl       2800.55
...                                                     ...           ...
843d87b5-902e-4336-9438-aa76d74e13e4     7858014473@okicici       9270.15
2dbbb577-4617-44b1-9a51-5fdf18ebb2ab  2795494339@okhdfcbank       2278.32
7c38e684-5968-432e-8acb-5bbe0f718fad       5207563362@okybl       4857.89
27624b55-fd6d-45ce-bbc5-0c2958d48865      9348631179@okaxis       9475.68
b792bf64-2047-4435-aac1-27ee95b134d6  1884708567@okhdfcbank       1426.60

                                      Status
Transaction ID
4d3db980-46cd-4158-a812-dcb77055d0d2       0
099ee548-2fc1-4811-bf92-559c467ca792       1
d4c05732-6b1b-4bab-90b9-efe09d252b99       1
e8df92ee-8b04-4133-af5a-5f412180c8ab       1
e7d675d3-04f1-419c-a841-7a04662560b7       1
...                                      ...
843d87b5-902e-4336-9438-aa76d74e13e4       1
2dbbb577-4617-44b1-9a51-5fdf18ebb2ab       0
7c38e684-5968-432e-8acb-5bbe0f718fad       0
27624b55-fd6d-45ce-bbc5-0c2958d48865       0
b792bf64-2047-4435-aac1-27ee95b134d6       1

[1000 rows x 7 columns]

In [21]:
#describing the data

In [22]:
df1.describe()

       Amount (INR)       Status
count   1000.000000  1000.000000
mean    4999.022930     0.502000
std     2873.484534     0.500246
min       28.520000     0.000000
25%     2521.620000     0.000000
50%     4951.435000     1.000000
75%     7315.835000     1.000000
max     9993.060000     1.000000

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 4d3db980-46cd-4158-a812-dcb77055d0d2 to b792bf64-2047-4435-aac1-27ee95b134d6
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Timestamp        1000 non-null   object
 1   Sender Name      1000 non-null   object
 2   Sender UPI ID    1000 non-null   object
 3   Receiver Name    1000 non-null   object
 4   Receiver UPI ID  1000 non-null   object
 5   Amount (INR)     1000 non-null   float64
 6   Status           1000 non-null   int32
dtypes: float64(1), int32(1), object(5)
memory usage: 58.6+ KB

In [24]:
#aligning the columns

In [25]:
 df1['Receiver Name'].str.strip("123._/")
df1

,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
Transaction ID,,,,,,,
4d3db980-46cd-4158-a812-dcb77055d0d2,22-06-2024 04:06,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,0
099ee548-2fc1-4811-bf92-559c467ca792,19-06-2024 06:04,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,1
d4c05732-6b1b-4bab-90b9-efe09d252b99,04-06-2024 04:56,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,1
e8df92ee-8b04-4133-af5a-5f412180c8ab,09-06-2024 09:56,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,1
e7d675d3-04f1-419c-a841-7a04662560b7,25-06-2024 08:38,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,1
...,...,...,...,...,...,...,...
843d87b5-902e-4336-9438-aa76d74e13e4,03-07-2024 23:15,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,1
2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,15-06-2024 15:42,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,0
7c38e684-5968-432e-8acb-5bbe0f718fad,18-06-2024 17:27,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,0
27624b55-fd6d-45ce-bbc5-0c2958d48865,05-06-2024 21:57,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,0
b792bf64-2047-4435-aac1-27ee95b134d6,21-06-2024 15:52,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,1

In [26]:
df1['Sender Name'].str.strip("123_./")
df1

,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
Transaction ID,,,,,,,
4d3db980-46cd-4158-a812-dcb77055d0d2,22-06-2024 04:06,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,0
099ee548-2fc1-4811-bf92-559c467ca792,19-06-2024 06:04,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,1
d4c05732-6b1b-4bab-90b9-efe09d252b99,04-06-2024 04:56,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,1
e8df92ee-8b04-4133-af5a-5f412180c8ab,09-06-2024 09:56,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,1
e7d675d3-04f1-419c-a841-7a04662560b7,25-06-2024 08:38,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,1
...,...,...,...,...,...,...,...
843d87b5-902e-4336-9438-aa76d74e13e4,03-07-2024 23:15,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,1
2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,15-06-2024 15:42,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,0
7c38e684-5968-432e-8acb-5bbe0f718fad,18-06-2024 17:27,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,0
27624b55-fd6d-45ce-bbc5-0c2958d48865,05-06-2024 21:57,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,0
b792bf64-2047-4435-aac1-27ee95b134d6,21-06-2024 15:52,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,1

In [27]:
#Finalized dataset

In [28]:
df1

,Timestamp,Sender Name,Sender UPI ID,Receiver Name,Receiver UPI ID,Amount (INR),Status
Transaction ID,,,,,,,
4d3db980-46cd-4158-a812-dcb77055d0d2,22-06-2024 04:06,Tiya Mall,4161803452@okaxis,Mohanlal Golla,7776849307@okybl,3907.34,0
099ee548-2fc1-4811-bf92-559c467ca792,19-06-2024 06:04,Mohanlal Bakshi,8908837379@okaxis,Mehul Sankaran,7683454560@okaxis,8404.55,1
d4c05732-6b1b-4bab-90b9-efe09d252b99,04-06-2024 04:56,Kismat Bora,4633654150@okybl,Diya Goel,2598130823@okicici,941.88,1
e8df92ee-8b04-4133-af5a-5f412180c8ab,09-06-2024 09:56,Ayesha Korpal,7018842771@okhdfcbank,Rhea Kothari,2246623650@okaxis,8926.00,1
e7d675d3-04f1-419c-a841-7a04662560b7,25-06-2024 08:38,Jivin Batta,1977143985@okybl,Baiju Issac,5245672729@okybl,2800.55,1
...,...,...,...,...,...,...,...
843d87b5-902e-4336-9438-aa76d74e13e4,03-07-2024 23:15,Anay Karan,7041132054@okhdfcbank,Dhanush Salvi,7858014473@okicici,9270.15,1
2dbbb577-4617-44b1-9a51-5fdf18ebb2ab,15-06-2024 15:42,Nirvaan Aurora,1200592114@okybl,Faiyaz Kara,2795494339@okhdfcbank,2278.32,0
7c38e684-5968-432e-8acb-5bbe0f718fad,18-06-2024 17:27,Bhamini Srinivasan,6922445535@okicici,Mishti Kala,5207563362@okybl,4857.89,0
27624b55-fd6d-45ce-bbc5-0c2958d48865,05-06-2024 21:57,Krish Kohli,4638471232@okhdfcbank,Sahil Bail,9348631179@okaxis,9475.68,0
b792bf64-2047-4435-aac1-27ee95b134d6,21-06-2024 15:52,Diya Trivedi,0385561234@oksbi,Dhanuk Mane,1884708567@okhdfcbank,1426.60,1